### ISSUE TITLE
Multi rebuild pods launched for a single file rebuilt

### ISSUE THREAD

**Issue by naderaly** [k8-proxy/go-k8s-infra#116] opened 2021-07-02 16:42 UTC
To replicate the issue:
1- run f2f with 1 thread by time 
2- check dashboard 

![image](https://user-images.githubusercontent.com/58347752/124305180-07902880-db65-11eb-8738-ac9a922e1f89.png)

**Comment by azopat** [comment] 2021-07-06 15:30
@naderaly  @mahnouman  i checked but couldn't reproduce the problem. It worked well for me
@naderaly  do you have it all the time ?

**Comment by naderaly** [comment] 2021-07-07 01:28
@azopat happened with me , mahmoud & @Lestat06 also , lets arrange a meeting tomorrow trying to reproduce it

**Comment by mahnouman** [comment] 2021-07-07 06:45
Work on this issue would be on https://github.com/k8-proxy/go-k8s-infra/issues/123

**Comment by GINAGC** [comment] 2021-07-14 16:24
Closing with https://github.com/k8-proxy/go-k8s-controller/issues/35

**Closed by GINAGC** 2021-07-14 16:24 UTC
